---
title: "Estudo de Variáveis"
output: html_notebook
---

```{r}
dados <- read.csv("Dados\\HR_comma_sep.csv", header = TRUE)
head(dados)
```

```{r}
summary(dados)
```
```{r}
#variável quantitativa contínua
#verificando a situação dos dados
summary(dados$satisfaction_level)
#Tbm poderia usar:
dados[dados$satisfaction_level<0 | dados$satisfaction_level>1 ,]$satisfaction_level
boxplot(dados$satisfaction_level)

histograma <- hist(dados$satisfaction_level)

#Elaborando um gráfico de frequência acumulutiva
histograma$counts <- cumsum(histograma$counts)
plot(histograma)
```


```{r}
#Variável quantitativa continua
summary(dados$last_evaluation)
dados[dados$last_evaluation<0 | dados$last_evaluation>1 ,]$last_evaluation
boxplot(dados$last_evaluation)

histograma <- hist(dados$last_evaluation)

histograma$counts <- cumsum(histograma$counts)
plot(histograma)

```
```{r}
#Variável quantitativa discreta
summary(dados$number_project)
dados[dados$number_project<0 ,]$number_project
boxplot(dados$number_project)

histograma <- hist(dados$number_project)

histograma$counts <- cumsum(histograma$counts)
plot(histograma)

```
```{r}
#variável quantitativa continua
summary(dados$average_montly_hours)
boxplot(dados$average_montly_hours)

histograma<- hist(dados$average_montly_hours)

histograma$counts <- cumsum(histograma$counts)
plot(histograma)
```
```{r}
#variavel quantitativa discreta
summary(dados$time_spend_company)
dados[dados$time_spend_company<0  ,]$time_spend_company
boxplot(dados$time_spend_company)

histograma<- hist(dados$time_spend_company)

histograma$counts <- cumsum(histograma$counts)
plot(histograma)

#Observando a quantidade de dados
library(dplyr)

grupo <- dados %>%
  group_by(time_spend_company) %>%
  count()
grupo
```
```{r}
#variavel quantitativa discreta
summary(dados$Work_accident)
boxplot(dados$Work_accident)

histograma <- hist(dados$Work_accident)
histograma$counts <- cumsum(histograma$counts)
plot(histograma)

grupo <- dados %>%
  group_by(Work_accident) %>%
  count()
grupo
```
```{r}
#variavel continua discreta
summary(dados$left)
boxplot(dados$left)

histograma<- hist(dados$left)
histograma$counts <- cumsum(histograma$counts)
plot(histograma)

grupo <- dados %>%
  group_by(left)%>%
  count()
grupo
```
```{r}
summary(dados$promotion_last_5years)
boxplot(dados$promotion_last_5years)

histograma<- hist(dados$promotion_last_5years)
histograma$counts<- cumsum(histograma$counts)
plot(histograma)

grupo <- dados %>%
  group_by(promotion_last_5years)%>%
  count()
grupo
```
```{r}
#variavel qualitativa nominal
summary(dados$Department)

x <- table(dados$Department)

x <- xtabs(~Department, data = dados)

x

departamento <- dados %>%
  group_by(Department)%>%
  count()
departamento

barplot(departamento$n,col= gray.colors(10), xlab="Spray", ylab="Total", names.arg=departamento$Department)
box()

```
```{r}
#install.packages("ggplot2") 
#install.packages("colorspace")
#install.packages("dplyr")
library("ggplot2")
library(dplyr)
```


```{r}
#Variavel qualitativa nominal
#Obtendo a frequenca absoluta de "Departament"
freqAbs<- as.data.frame(table(dados$Department)) 
freqAbs
#Renomeando colunas
colnames(freqAbs) = c("Departamento","Funcionarios")
freqAbs
```
```{r}
#Elaborando o grafico de barras horizontal da frequencia absoluta
ggplot(freqAbs, aes(x = Funcionarios, y = Departamento)) +
  geom_col(fill = "gray70") +
  geom_text(aes(label= Funcionarios)) +
  theme_minimal()
```
```{r}
#Criando a coluna da frequencia relativa 
freqAbs <- freqAbs |> 
  dplyr::mutate(PercFuncionarios = paste0(sprintf("%4.1f", Funcionarios / sum(Funcionarios) * 100), "%"))

freqAbs

```
```{r}
#Elaborando o grafico de barras horizontal da frequencia relativa
ggplot(freqAbs, aes(x = PercFuncionarios, y = Departamento)) +
  geom_col(fill = "gray70") +
  theme_minimal()
```
```{r}
#Variavel qualitativa ordinal
freqAbs<- as.data.frame(table(dados$salary)) 
freqAbs

colnames(freqAbs) = c("TipoSalario","Funcionarios")
freqAbs
```
```{r}
#Organizando se acordo com nivel
freqAbs$TipoSalario <- factor(freqAbs$TipoSalario,                          
                  levels = c("low", "medium", "high"))

ggplot(freqAbs, aes(x = TipoSalario, y = Funcionarios)) +
  geom_col(fill = "gray70") +
  geom_text(aes(label= Funcionarios)) +
  theme_minimal()
```
```{r}
#ordenando pela quantidade de funcionarios(menor para o maior)
freqAbs$TipoSalario <- factor(freqAbs$TipoSalario, levels = freqAbs$TipoSalario[order(freqAbs$Funcionarios)])

ggplot(freqAbs, aes(x = TipoSalario, y = Funcionarios)) +
  geom_col(fill = "gray70") +
  geom_text(aes(label= Funcionarios)) +
  theme_minimal()
```
```{r}
freqAbs <- freqAbs |> 
  dplyr::mutate(PercFuncionarios = paste0(sprintf("%4.1f", Funcionarios / sum(Funcionarios) * 100), "%"))

freqAbs
```
```{r}
freqAbs$TipoSalario <- factor(freqAbs$TipoSalario,                          
                  levels = c("low", "medium", "high"))

ggplot(freqAbs, aes(x = TipoSalario, y = PercFuncionarios)) +
  geom_col(fill = "gray70") +
  theme_minimal()
```
```{r}
freqAbs$TipoSalario <- factor(freqAbs$TipoSalario,                          
                  levels = c("low", "medium", "high"))

ggplot(freqAbs, aes(x = "", y = PercFuncionarios, fill = TipoSalario)) +
  geom_col(color = "black") +
  coord_polar(theta = "y")+
  geom_text(aes(label = PercFuncionarios),
            position = position_stack(vjust = 0.5)) +
  scale_fill_grey()+
  theme_void()
```




